version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devdbuser
      - DB_PASS=changeme
      - AWS_ACCESS_KEY_ID=AKIA22KQXHYZCL4RDB75
      - AWS_SECRET_KEY_ID=6aUoMvwafP3AoRuXm+144ks60YKiWSFAC4O49jzj
      - AWS_STORAGE_BUCKET_NAME=ecommerce-back-images
      - AWS_S3_REGION_NAME=sa-east-1
      - EMAIL_HOST=sandbox.smtp.mailtrap.io
      - EMAIL_HOST_USER=aed94ea792cedd
      - EMAIL_HOST_PASSWORD=ae8936ec05a14d
      - EMAIL_PORT=2525


    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devdbuser
      - POSTGRES_PASSWORD=changeme
    ports:
      - "5432:5432"

volumes:
  dev-db-data:
  dev-static-data: